import { Theme, ThemeId, Achievement, UserStats, Language } from './types';

export const THEMES: Record<ThemeId, Theme> = {
  [ThemeId.Midnight]: {
    id: ThemeId.Midnight,
    name: 'Midnight',
    colors: {
      bg: 'bg-slate-900',
      surface: 'bg-slate-800',
      primary: 'text-indigo-400',
      secondary: 'text-slate-400',
      text: 'text-white',
      textMuted: 'text-slate-400',
      accent: 'bg-indigo-500',
      priorityHigh: 'bg-red-500',
      priorityMed: 'bg-amber-500',
      priorityLow: 'bg-slate-500',
    },
  },
  [ThemeId.Sunrise]: {
    id: ThemeId.Sunrise,
    name: 'Sunrise',
    colors: {
      bg: 'bg-orange-50',
      surface: 'bg-white',
      primary: 'text-orange-500',
      secondary: 'text-stone-400',
      text: 'text-stone-800',
      textMuted: 'text-stone-500',
      accent: 'bg-orange-500',
      priorityHigh: 'bg-red-500',
      priorityMed: 'bg-orange-400',
      priorityLow: 'bg-stone-400',
    },
  },
  [ThemeId.Forest]: {
    id: ThemeId.Forest,
    name: 'Forest',
    colors: {
      bg: 'bg-emerald-950',
      surface: 'bg-emerald-900',
      primary: 'text-emerald-400',
      secondary: 'text-emerald-600',
      text: 'text-emerald-50',
      textMuted: 'text-emerald-400',
      accent: 'bg-emerald-600',
      priorityHigh: 'bg-red-500',
      priorityMed: 'bg-yellow-500',
      priorityLow: 'bg-emerald-700',
    },
  },
  [ThemeId.Ocean]: {
    id: ThemeId.Ocean,
    name: 'Ocean',
    colors: {
      bg: 'bg-cyan-950',
      surface: 'bg-cyan-900',
      primary: 'text-cyan-400',
      secondary: 'text-cyan-600',
      text: 'text-cyan-50',
      textMuted: 'text-cyan-400',
      accent: 'bg-cyan-600',
      priorityHigh: 'bg-rose-500',
      priorityMed: 'bg-amber-400',
      priorityLow: 'bg-cyan-700',
    },
  },
  [ThemeId.Berry]: {
    id: ThemeId.Berry,
    name: 'Berry',
    colors: {
      bg: 'bg-fuchsia-950',
      surface: 'bg-fuchsia-900',
      primary: 'text-pink-400',
      secondary: 'text-pink-600',
      text: 'text-pink-50',
      textMuted: 'text-pink-400',
      accent: 'bg-pink-600',
      priorityHigh: 'bg-red-500',
      priorityMed: 'bg-pink-400',
      priorityLow: 'bg-fuchsia-800',
    },
  },
};

export const DEFAULT_FOCUS_TIME = 25 * 60; // 25 minutes
export const SHORT_BREAK_TIME = 5 * 60; // 5 minutes

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_step',
    title: { en: 'First Step', zh: '迈出第一步' },
    description: { en: 'Complete your first task', zh: '完成你的第一个任务' },
    icon: '🎯',
    condition: (stats: UserStats) => stats.totalTasksCompleted >= 1
  },
  {
    id: 'productivity_master',
    title: { en: 'Productivity Master', zh: '效率大师' },
    description: { en: 'Complete 50 tasks', zh: '累计完成50个任务' },
    icon: '🚀',
    condition: (stats: UserStats) => stats.totalTasksCompleted >= 50
  },
  {
    id: 'focus_novice',
    title: { en: 'Focus Novice', zh: '专注新手' },
    description: { en: 'Focus for 25 minutes', zh: '累计专注25分钟' },
    icon: '🌱',
    condition: (stats: UserStats) => stats.totalFocusMinutes >= 25
  },
  {
    id: 'deep_worker',
    title: { en: 'Deep Worker', zh: '深度工作者' },
    description: { en: 'Focus for 200 minutes', zh: '累计专注200分钟' },
    icon: '🧠',
    condition: (stats: UserStats) => stats.totalFocusMinutes >= 200
  },
  {
    id: 'zen_master',
    title: { en: 'Zen Master', zh: '禅意大师' },
    description: { en: 'Complete 100 tasks and 500 mins focus', zh: '完成100个任务且专注500分钟' },
    icon: '🧘',
    condition: (stats: UserStats) => stats.totalTasksCompleted >= 100 && stats.totalFocusMinutes >= 500
  }
];

export const TRANSLATIONS = {
  en: {
    app_title: "ZenTask",
    focus: "Focus",
    tasks: "Tasks",
    stats: "Stats",
    wellness: "Wellness",
    summary: "Summary",
    add_task_placeholder: "Add task... use #tag for tags",
    tasks_header: "Tasks",
    done_header: "Done",
    no_tasks: "No tasks found.",
    use_hash_for_tags: "Use # for tags",
    priority_all: "All Priorities",
    priority_high: "High",
    priority_medium: "Medium",
    priority_low: "Low",
    tags_all: "All Tags",
    break: "Break",
    session_finished: "Session Finished!",
    wellness_title: "Wellness Alerts",
    wellness_desc: "Active health reminders",
    water_interval: "Water Interval",
    stretch_interval: "Stretch Interval",
    notification_style: "Notification Style",
    sound: "Sound",
    mode: "Mode",
    sound_beep: "Simple Beep",
    sound_chime: "Gentle Chime",
    sound_pulse: "Pulse",
    mode_both: "Sound & Visual",
    mode_sound: "Sound Only",
    mode_visual: "Visual Only",
    reminders_paused: "Reminders paused",
    reminders_active: "Reminders active",
    stats_title: "Your Progress",
    tasks_done: "Tasks Done",
    focus_mins: "Focus Mins",
    achievements: "Achievements",
    summary_title: "Daily Review",
    summary_desc: "{count} tasks completed today",
    summary_placeholder: "Ready to wrap up? Let AI analyze your day and give you a boost.",
    generate_btn: "Generate Summary",
    generating: "Generating...",
    refresh: "Refresh",
    api_error: "API Key not found or error.",
    summary_prompt_error: "It looks like you haven't completed any tasks yet.",
  },
  zh: {
    app_title: "ZenTask",
    focus: "专注",
    tasks: "待办",
    stats: "统计",
    wellness: "健康",
    summary: "总结",
    add_task_placeholder: "添加任务... 使用 #标签",
    tasks_header: "进行中",
    done_header: "已完成",
    no_tasks: "暂无任务",
    use_hash_for_tags: "使用 # 添加标签",
    priority_all: "所有优先级",
    priority_high: "高",
    priority_medium: "中",
    priority_low: "低",
    tags_all: "所有标签",
    break: "休息",
    session_finished: "专注结束！",
    wellness_title: "健康提醒",
    wellness_desc: "定时活动与喝水",
    water_interval: "喝水间隔",
    stretch_interval: "活动间隔",
    notification_style: "通知样式",
    sound: "提示音",
    mode: "提醒方式",
    sound_beep: "滴滴声",
    sound_chime: "风铃声",
    sound_pulse: "脉冲声",
    mode_both: "声音 + 闪烁",
    mode_sound: "仅声音",
    mode_visual: "仅闪烁",
    reminders_paused: "提醒已暂停",
    reminders_active: "提醒运行中",
    stats_title: "你的进度",
    tasks_done: "完成任务",
    focus_mins: "专注时长(分)",
    achievements: "成就勋章",
    summary_title: "每日总结",
    summary_desc: "今日完成 {count} 个任务",
    summary_placeholder: "准备结束一天了吗？让AI为你生成今日总结。",
    generate_btn: "生成总结",
    generating: "生成中...",
    refresh: "刷新",
    api_error: "未找到API密钥或发生错误。",
    summary_prompt_error: "看来你今天还没完成任何任务，快去行动吧！",
  }
};
